<?php /** @var \Astound\InfoBar\Block\Notification $block */ ?>
<?php if($block->getNotifCount()): ?>
<div>Notifications</div>
    <?php foreach($block->getNotifications()->getItems() as $item): ?>
        <div style="background: <?php echo $item->getBackgroundColor();?>">
            <p><?php echo $item->getTitle(); ?></p>
            <p><?php echo $item->getContent(); ?></p>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
